name: BookSmartly
language: typescript
framework: nextjs
description: BookSmartly project - healthcare appointment booking platform
version: "1.0.0"

directories:
  source: "."
  build: ".next"
  tests: "__tests__"

file_patterns:
  source:
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.json"
    - "**/*.md"
  ignore:
    - "node_modules/**"
    - ".next/**"
    - ".git/**"
    - "dist/**"
    - "build/**"

tools:
  linter: "eslint"
  formatter: "prettier"
  package_manager: "npm"

environment:
  node_version: "18+"
  package_manager: "npm"