name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
        
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@145.223.73.170 << 'EOF'
          cd /var/www/booksmartly
          
          # Pull latest changes
          git stash
          git pull origin main
          
          # Install/update dependencies
          cd backend && npm install --production
          cd ../frontend && npm install
          cd ..
          
          # Restart services
          pm2 restart booksmartly-backend
          pm2 restart booksmartly-ml
          pm2 restart booksmartly-chatbot
          pm2 restart booksmartly-report
          pm2 restart booksmartly-sentiment
          
          # Show status
          pm2 list
        EOF